#version 450

#include "sph/sph_spring_common.glsl"

layout(local_size_x = 64) in;

layout(std430, binding = 0)
buffer Springs
{
    Spring springs[];
};

layout(std430, binding = 1)
buffer SpringHeads
{
    uint springHeads[];
};

layout(push_constant)
uniform PushConstants
{
    uint maxSprings;
    uint particleCount;
} pc;

void main()
{
    uint index = gl_GlobalInvocationID.x;

    if (index < pc.maxSprings)
    {
        springs[index].pairKey = EMPTY_SPRING_KEY;
    }

    if (index < pc.particleCount)
    {
        springHeads[index] = INVALID_SPRING_INDEX;
    }
}