#version 450

layout(local_size_x = 64) in;

layout(std430, binding = 0)
buffer Positions
{
    vec4 positions[];
};

layout(std430, binding = 1)
readonly buffer PositionDeltas
{
    vec4 positionDeltas[];
};

layout(push_constant)
uniform PushConstants
{
    uint particleCount;
} pc;

void main()
{
    uint i = gl_GlobalInvocationID.x;

    if (i >= pc.particleCount)
    {
        return;
    }

    positions[i].xyz += positionDeltas[i].xyz;
}