#version 450

#include "sph/sph_spring_common.glsl"

layout(local_size_x = 64) in;

layout(std430, binding = 0)
writeonly buffer SpringHeads
{
    uint springHeads[];
};

layout(std430, binding = 1)
buffer SpringLookupHeads
{
    uint springLookupHeads[];
};

layout(push_constant)
uniform PushConstants
{
    uint particleCount;
    uint springCounterIndex;
} pc;

void main()
{
    uint i = gl_GlobalInvocationID.x;

    if (i < pc.particleCount)
    {
        springHeads[i] = INVALID_SPRING_INDEX;
        springLookupHeads[i] = INVALID_SPRING_INDEX;
    }

    if (i == 0u)
    {
        springLookupHeads[pc.springCounterIndex] = 0u;
    }
}