#version 450

layout(local_size_x = 64) in;

layout(std430, binding = 0)
readonly buffer Positions
{
    vec4 positions[];
};

layout(std430, binding = 1)
readonly buffer Velocities
{
    vec4 velocities[];
};

layout(std430, binding = 2)
readonly buffer ParticleIndices
{
    uint particleIndices[];
};

layout(std430, binding = 3)
readonly buffer CellStarts
{
    uint cellStarts[];
};

layout(std430, binding = 4)
readonly buffer CellEnds
{
    uint cellEnds[];
};

layout(std430, binding = 5)
writeonly buffer VelocityDeltas
{
    vec4 velocityDeltas[];
};

layout(push_constant)
uniform PushConstants
{
    float dt;
    float smoothingRadius;
    float sigma;
    float beta;

    uint particleCount;
    uint gridWidth;
    uint gridHeight;
    uint padding;

    vec4 boundsMin;
} pc;

void main()
{
    uint i = gl_GlobalInvocationID.x;

    if (i >= pc.particleCount)
    {
        return;
    }

    vec3 positionA = positions[i].xyz;

    vec3 velocityA = velocities[i].xyz;

    vec2 localPosition = positionA.xy - pc.boundsMin.xy;

    ivec2 cell = ivec2(floor(localPosition / pc.smoothingRadius));

    vec3 velocityDelta = vec3(0.0);

    for (int y = -1; y <= 1; ++y)
    {
        for (int x = -1; x <= 1; ++x)
        {
            ivec2 neighbourCell = cell + ivec2(x, y);

            if (neighbourCell.x < 0 || neighbourCell.y < 0 || neighbourCell.x >= int(pc.gridWidth) || neighbourCell.y >= int(pc.gridHeight))
            {
                continue;
            }

            uint cellKey = uint(neighbourCell.y) * pc.gridWidth + uint(neighbourCell.x);

            uint start = cellStarts[cellKey];

            uint end = cellEnds[cellKey];

            if (start == 0xFFFFFFFFu || end == 0xFFFFFFFFu)
            {
                continue;
            }

            for (uint sortedIndex = start; sortedIndex < end;  ++sortedIndex)
            {
                uint j = particleIndices[sortedIndex];

                if (j == i)
                {
                    continue;
                }

                vec3 direction = positions[j].xyz - positionA;

                float distance = length(direction);

                if (distance <= 0.000001 || distance >= pc.smoothingRadius)
                {
                    continue;
                }

                float q = distance / pc.smoothingRadius;

                vec3 normalizedDirection = direction / distance;

                float u = dot(velocityA - velocities[j].xyz, normalizedDirection);

                if (u <= 0.0)
                {
                    continue;
                }

                float term = pc.dt * (1.0 - q) * (pc.sigma * u + pc.beta * u * u);

                velocityDelta -= normalizedDirection * term * 0.5;
            }
        }
    }

    velocityDeltas[i] = vec4(velocityDelta, 0.0);
}