#version 450

layout(local_size_x = 64) in;

layout(std430, binding = 0)
writeonly buffer CellStarts
{
    uint cellStarts[];
};

layout(std430, binding = 1)
writeonly buffer CellEnds
{
    uint cellEnds[];
};

layout(push_constant)
uniform PushConstants
{
    uint cellCount;
} pc;

void main()
{
    uint i = gl_GlobalInvocationID.x;

    if (i >= pc.cellCount)
    {
        return;
    }

    cellStarts[i] = 0xFFFFFFFFu;
    cellEnds[i] = 0xFFFFFFFFu;
}