#version 450

layout(local_size_x = 64) in;

layout(std430, binding = 0)
buffer Velocities
{
    vec4 velocities[];
};

layout(push_constant)
uniform PushConstants
{
    float dt;
    float gravity;
    uint particleCount;
    uint padding;

    vec4 gravityDirection;
} pc;

void main()
{
    uint i = gl_GlobalInvocationID.x;

    if (i >= pc.particleCount)
    {
        return;
    }

    velocities[i].xyz += pc.gravityDirection.xyz * pc.gravity * pc.dt;
}