#version 450

layout(local_size_x = 64) in;

layout(std430, binding = 0)
readonly buffer Positions
{
    vec4 positions[];
};

layout(std430, binding = 1)
readonly buffer PreviousPositions
{
    vec4 previousPositions[];
};

layout(std430, binding = 2)
writeonly buffer Velocities
{
    vec4 velocities[];
};

layout(push_constant)
uniform PushConstants
{
    float dt;
    float velocityDamping;
    float maxVelocity;
    uint particleCount;
} pc;

void main()
{
    uint i = gl_GlobalInvocationID.x;

    if (i >= pc.particleCount)
    {
        return;
    }

    vec3 velocity = (positions[i].xyz - previousPositions[i].xyz) / pc.dt;

    velocity *= pc.velocityDamping;

    float velocitySquared = dot(velocity, velocity);

    float maxVelocitySquared = pc.maxVelocity * pc.maxVelocity;

    if (velocitySquared > maxVelocitySquared)
    {
        velocity *= pc.maxVelocity / sqrt(velocitySquared);
    }

    velocities[i] = vec4(velocity, 0.0);
}
