#version 450

layout(local_size_x = 64) in;

layout(std430, binding = 0)
buffer Positions
{
    vec4 positions[];
};

layout(std430, binding = 1)
buffer PreviousPositions
{
    vec4 previousPositions[];
};

layout(push_constant)
uniform PushConstants
{
    float particleRadius;
    uint particleCount;
    uint padding0;
    uint padding1;

    vec4 boundsPosition;
    vec4 boundsSize;
} pc;

void main()
{
    uint i = gl_GlobalInvocationID.x;

    if (i >= pc.particleCount)
    {
        return;
    }

    vec3 position = positions[i].xyz;

    vec3 previousPosition = previousPositions[i].xyz;

    vec2 halfSize = pc.boundsSize.xy * 0.5;

    float left = pc.boundsPosition.x - halfSize.x + pc.particleRadius;

    float right = pc.boundsPosition.x + halfSize.x - pc.particleRadius;

    float bottom = pc.boundsPosition.y - halfSize.y + pc.particleRadius;

    float top = pc.boundsPosition.y + halfSize.y - pc.particleRadius;

    if (position.x < left)
    {
        position.x = left;
        previousPosition.x = left;
    }

    if (position.x > right)
    {
        position.x = right;
        previousPosition.x = right;
    }

    if (position.y < bottom)
    {
        position.y = bottom;
        previousPosition.y = bottom;
    }

    if (position.y > top)
    {
        position.y = top;
        previousPosition.y = top;
    }

    positions[i] = vec4(position, 0.0);

    previousPositions[i] = vec4(previousPosition, 0.0);
}