#version 450

#include "sph/sph_spring_common.glsl"

layout(local_size_x = 256) in;

layout(std430, binding = 0)
buffer SpringLookup
{
    SpringLookupEntry springLookup[];
};

layout(push_constant)
uniform PushConstants
{
    uint lookupCapacity;
} pc;

void main()
{
    uint i = gl_GlobalInvocationID.x;

    if (i >= pc.lookupCapacity)
    {
        return;
    }

    springLookup[i].pairKey = INVALID_SPRING_INDEX;
}