#ifndef AIKO_DESCRIPTOR_ABI_GLSL
#define AIKO_DESCRIPTOR_ABI_GLSL

// Graphics sets
#define AIKO_GRAPHICS_FRAME_SET 0
#define AIKO_GRAPHICS_MATERIAL_SET 1
#define AIKO_GRAPHICS_GPU_READ_SET 2

// Graphics set 0
#define AIKO_GRAPHICS_FRAME_BINDING 0

// Graphics set 1
#define AIKO_MATERIAL_UBO_BINDING 0
#define AIKO_MATERIAL_TEXTURE_BINDING 1

// Graphics set 2
#define AIKO_MAX_GPU_READ_BINDINGS 16

// Compute
#define AIKO_COMPUTE_SET 0

#define AIKO_MAX_COMPUTE_BUFFER_BINDINGS 4
#define AIKO_MAX_COMPUTE_IMAGE_BINDINGS 8

#define AIKO_COMPUTE_BUFFER_BINDING_BASE 0

#define AIKO_COMPUTE_IMAGE_BINDING_BASE \
    (AIKO_COMPUTE_BUFFER_BINDING_BASE + \
     AIKO_MAX_COMPUTE_BUFFER_BINDINGS)

#define AIKO_COMPUTE_FRAME_BINDING \
    (AIKO_COMPUTE_IMAGE_BINDING_BASE + \
     AIKO_MAX_COMPUTE_IMAGE_BINDINGS)

#define AIKO_COMPUTE_BUFFER_BINDING(slot) \
    (AIKO_COMPUTE_BUFFER_BINDING_BASE + slot)

#define AIKO_COMPUTE_IMAGE_BINDING(slot) \
    (AIKO_COMPUTE_IMAGE_BINDING_BASE + slot)

#endif
