#ifndef AIKO_COMPUTE_GLSL
#define AIKO_COMPUTE_GLSL

#define AIKO_MAX_COMPUTE_BUFFER_BINDINGS 4
#define AIKO_COMPUTE_BUFFER_BINDING(slot) slot
#define AIKO_COMPUTE_IMAGE_BINDING(slot) (AIKO_MAX_COMPUTE_BUFFER_BINDINGS + slot)

#endif