#version 450

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) readonly buffer InputBuffer
{
    vec4 values[];
} inputBuffer;

layout(set = 0, binding = 1) writeonly buffer OutputBuffer
{
    vec4 values[];
} outputBuffer;

void main()
{
    uint index = gl_GlobalInvocationID.x;

    outputBuffer.values[index] =
        inputBuffer.values[index] * 2.0;
}