#version 450

layout(std430, set = 0, binding = 0) buffer ParticlePositionBuffer
{
    vec4 u_pos[];
};

layout(std430, set = 0, binding = 1) buffer ParticleVelocityBuffer
{
    vec4 u_vel[];
};

layout(std430, set = 0, binding = 2) buffer ParticleLifeBuffer
{
    vec4 u_life[];
};

layout(push_constant) uniform ParticlesInitPushConstants
{
    vec4 u_params;
    vec4 u_emitterPos;
};

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= uint(u_params.x))
    {
        return;
    }

    u_pos[idx] = vec4(u_emitterPos.xyz, 1.0);
    u_vel[idx] = vec4(0.0, 0.0, 0.0, 0.0);
    u_life[idx] = vec4(0.0, u_params.y, 0.0, 0.0);
}
