#version 450

struct Particle {
	vec4 position;
	vec4 velocity;
    vec4 color;
};

layout (binding = 0) uniform ParameterUBO {
    float deltaTime;
} ubo;

layout(std140, binding = 1) readonly buffer ParticleSSBOIn {
   Particle particlesIn[ ];
};

layout(std140, binding = 2) buffer ParticleSSBOOut {
   Particle particlesOut[ ];
};

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint index = gl_GlobalInvocationID.x;

    Particle particleIn = particlesIn[index];

    particlesOut[index].position.xyz = particleIn.position.xyz + particleIn.velocity.xyz * ubo.deltaTime;
    particlesOut[index].velocity.xyz = particleIn.velocity.xyz;

    particlesOut[index].position.w = particleIn.position.w;
    particlesOut[index].velocity.w = particleIn.velocity.w;
    particlesOut[index].color = particleIn.color;

    // Flip movement at window border
    if ((particlesOut[index].position.x <= -1.0) || (particlesOut[index].position.x >= 1.0)) {
        particlesOut[index].velocity.x = -particlesOut[index].velocity.x;
    }
    if ((particlesOut[index].position.y <= -1.0) || (particlesOut[index].position.y >= 1.0)) {
        particlesOut[index].velocity.y = -particlesOut[index].velocity.y;
    }
    if ((particlesOut[index].position.z <= -1.0) || (particlesOut[index].position.z >= 1.0)) {
        particlesOut[index].velocity.z = -particlesOut[index].velocity.z;
    }

}
