#version 450

layout(local_size_x = 64) in;

const uint EMPTY_SPRING_KEY = 0xFFFFFFFFu;

struct Spring
{
    uint pairKey;
    float restLength;
    uint enabled;
    uint padding;
};

layout(std430, binding = 0)
readonly buffer Positions
{
    vec4 positions[];
};

layout(std430, binding = 1)
readonly buffer Springs
{
    Spring springs[];
};

layout(std430, binding = 2)
writeonly buffer PositionDeltas
{
    vec4 positionDeltas[];
};

layout(push_constant)
uniform PushConstants
{
    float dt;
    float smoothingRadius;
    float springStiffness;
    uint particleCount;

    uint maxSprings;
    uint padding0;
    uint padding1;
    uint padding2;
} pc;

uint getParticleA(uint pairKey)
{
    return pairKey >> 16;
}

uint getParticleB(uint pairKey)
{
    return pairKey & 0xFFFFu;
}

void main()
{
    uint i = gl_GlobalInvocationID.x;

    if (i >= pc.particleCount)
    {
        return;
    }

    vec3 delta = vec3(0.0);

    for (uint springIndex = 0; springIndex < pc.maxSprings;  ++springIndex)
    {
        Spring spring = springs[springIndex];

        if (spring.pairKey == EMPTY_SPRING_KEY || spring.enabled == 0u)
        {
            continue;
        }

        uint particleA = getParticleA(spring.pairKey);

        uint particleB = getParticleB(spring.pairKey);

        bool isParticleA = particleA == i;

        bool isParticleB = particleB == i;

        if (isParticleA == false && isParticleB == false)
        {
            continue;
        }

        vec3 positionA = positions[particleA].xyz;

        vec3 positionB = positions[particleB].xyz;

        vec3 direction = positionB - positionA;

        float distance = length(direction);

        if (distance <= 0.000001)
        {
            continue;
        }

        vec3 normalizedDirection = direction / distance;

        float displacementTerm = pc.dt * pc.dt * pc.springStiffness * (1.0 - spring.restLength / pc.smoothingRadius) * (spring.restLength - distance);

        vec3 displacement = normalizedDirection * displacementTerm * 0.5;

        if (isParticleA)
        {
            delta -= displacement;
        }
        else
        {
            delta += displacement;
        }
    }

    positionDeltas[i] = vec4(delta, 0.0);
}