#version 450

layout(local_size_x = 64) in;

layout(std430, binding = 0)
buffer Velocities
{
    vec4 velocities[];
};

layout(std430, binding = 1)
readonly buffer VelocityDeltas
{
    vec4 velocityDeltas[];
};

layout(push_constant)
uniform PushConstants
{
    uint particleCount;
} pc;

void main()
{
    uint i = gl_GlobalInvocationID.x;

    if (i >= pc.particleCount)
    {
        return;
    }

    velocities[i].xyz += velocityDeltas[i].xyz;
}