#version 450

layout(local_size_x = 64) in;

const uint EMPTY_SPRING_KEY = 0xFFFFFFFFu;

struct Spring
{
    uint pairKey;
    float restLength;
    uint enabled;
    uint padding;
};

layout(std430, binding = 0)
readonly buffer Positions
{
    vec4 positions[];
};

layout(std430, binding = 1)
buffer Springs
{
    Spring springs[];
};

layout(push_constant)
uniform PushConstants
{
    float dt;
    float gamma;
    float plasticity;
    float smoothingRadius;

    uint maxSprings;
    uint padding0;
    uint padding1;
    uint padding2;
} pc;

uint getParticleA(uint pairKey)
{
    return pairKey >> 16;
}

uint getParticleB(uint pairKey)
{
    return pairKey & 0xFFFFu;
}

void main()
{
    uint springIndex = gl_GlobalInvocationID.x;

    if (springIndex >= pc.maxSprings)
    {
        return;
    }

    Spring spring = springs[springIndex];

    if (spring.pairKey == EMPTY_SPRING_KEY || spring.enabled == 0u)
    {
        return;
    }

    uint particleA = getParticleA(spring.pairKey);
    uint particleB = getParticleB(spring.pairKey);

    vec3 positionA = positions[particleA].xyz;
    vec3 positionB = positions[particleB].xyz;

    float distance = length(positionA - positionB);

    float deformation = pc.gamma * spring.restLength;

    if (distance > spring.restLength + deformation)
    {
        spring.restLength += pc.dt * pc.plasticity * (distance - spring.restLength - deformation);
    }
    else if (distance < spring.restLength - deformation)
    {
        spring.restLength -= pc.dt * pc.plasticity * ( spring.restLength - deformation - distance );
    }

    if (spring.restLength > pc.smoothingRadius)
    {
        spring.enabled = 0;
    }

    springs[springIndex] = spring;
}