#version 450

layout(local_size_x = 64) in;

layout(std430, binding = 0)
readonly buffer Positions
{
    vec4 positions[];
};

layout(std430, binding = 1)
readonly buffer ParticleIndices
{
    uint particleIndices[];
};

layout(std430, binding = 2)
readonly buffer CellStarts
{
    uint cellStarts[];
};

layout(std430, binding = 3)
readonly buffer CellEnds
{
    uint cellEnds[];
};

layout(std430, binding = 4)
writeonly buffer Densities
{
    vec4 densities[];
};

layout(std430, binding = 5)
writeonly buffer Pressures
{
    vec4 pressures[];
};

layout(push_constant)
uniform PushConstants
{
    float smoothingRadius;
    float restDensity;
    float pressureStiffness;
    float nearPressureStiffness;

    uint particleCount;
    uint gridWidth;
    uint gridHeight;
    uint padding;

    vec4 boundsMin;
} pc;

void main()
{
    uint i = gl_GlobalInvocationID.x;

    if (i >= pc.particleCount)
    {
        return;
    }

    vec3 positionA = positions[i].xyz;

    ivec2 cell = ivec2(floor((positionA.xy - pc.boundsMin.xy) / pc.smoothingRadius));

    float density = 0.0;
    float densityNear = 0.0;

    for (int y = -1; y <= 1; ++y)
    {
        for (int x = -1; x <= 1; ++x)
        {
            ivec2 neighbourCell = cell + ivec2(x, y);

            if (neighbourCell.x < 0 || neighbourCell.y < 0 || neighbourCell.x >= int(pc.gridWidth) || neighbourCell.y >= int(pc.gridHeight))
            {
                continue;
            }

            uint key = uint(neighbourCell.y) * pc.gridWidth + uint(neighbourCell.x);

            uint start = cellStarts[key];
            uint end = cellEnds[key];

            if (start == 0xFFFFFFFFu || end == 0xFFFFFFFFu)
            {
                continue;
            }

            for (uint sortedIndex = start; sortedIndex < end;  ++sortedIndex)
            {
                uint j = particleIndices[sortedIndex];

                if (j == i)
                {
                    continue;
                }

                vec3 direction = positions[j].xyz - positionA;

                float distance = length(direction);

                float q = distance / pc.smoothingRadius;

                if (q < 1.0)
                {
                    float oneMinusQ = 1.0 - q;

                    float oneMinusQ2 =oneMinusQ * oneMinusQ;

                    density += oneMinusQ2;

                    densityNear += oneMinusQ2 * oneMinusQ;
                }
            }
        }
    }

    float pressure = pc.pressureStiffness * (density - pc.restDensity);
    float pressureNear = pc.nearPressureStiffness * densityNear;

    densities[i] = vec4(density, densityNear, 0.0, 0.0);

    pressures[i] = vec4(pressure, pressureNear, 0.0, 0.0);
}