#version 450

layout(local_size_x = 64) in;

layout(std430, binding = 0)
buffer Positions
{
    vec4 positions[];
};

layout(std430, binding = 1)
buffer Velocities
{
    vec4 velocities[];
};

layout(push_constant)
uniform PushConstants
{
    float dt;
    float gravity;
    float particleRadius;
    uint particleCount;

    vec4 gravityDirection;
    vec4 boundsPosition;
    vec4 boundsSize;
} pc;

void main()
{
    uint i = gl_GlobalInvocationID.x;

    if (i >= pc.particleCount)
    {
        return;
    }

    vec3 velocity = velocities[i].xyz;

    vec3 position =  positions[i].xyz;

    velocity += pc.gravityDirection.xyz * pc.gravity * pc.dt;

    position += velocity * pc.dt;

    vec2 halfSize =  pc.boundsSize.xy * 0.5;
    float left = pc.boundsPosition.x - halfSize.x + pc.particleRadius;
    float right = pc.boundsPosition.x + halfSize.x - pc.particleRadius;
    float bottom = pc.boundsPosition.y - halfSize.y + pc.particleRadius;
    float top = pc.boundsPosition.y + halfSize.y - pc.particleRadius;

    if (position.x < left)
    {
        position.x = left;
        velocity.x = 0.0;
    }

    if (position.x > right)
    {
        position.x = right;
        velocity.x = 0.0;
    }

    if (position.y < bottom)
    {
        position.y = bottom;
        velocity.y = 0.0;
    }

    if (position.y > top)
    {
        position.y = top;
        velocity.y = 0.0;
    }

    velocities[i] = vec4(velocity, 0.0);
    positions[i] = vec4(position, 0.0);

}
