function(aiko_add_target target)
    if(TARGET ${target})
        set_property(TARGET ${target} PROPERTY FOLDER "Aiko")
    else()
        message(FATAL_ERROR "aiko_add_target: target '${target}' does not exist")
    endif()
endfunction()

function(aiko_add_example target)
    if(TARGET ${target})
        set_property(TARGET ${target} PROPERTY FOLDER "AikoExamples")
    else()
        message(FATAL_ERROR "aiko_add_example: target '${target}' does not exist")
    endif()
endfunction()