if(NOT DEFINED INPUT_FILE)
    message(FATAL_ERROR "INPUT_FILE is required")
endif()

if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is required")
endif()

file(READ "${INPUT_FILE}" SHADERTOY_SOURCE)

get_filename_component(OUTPUT_DIR "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")

set(SHADERTOY_HEADER [=[
#version 450

#include "aiko_descriptor_abi.glsl"

// Generated by Aiko's ShaderToy adapter.
// Do not edit this generated file directly.

layout(
    set = AIKO_GRAPHICS_MATERIAL_SET,
    binding = AIKO_MATERIAL_UBO_BINDING,
    std140
) uniform ShaderToyUniforms
{
    vec3 iResolution;
    float iTime;

    float iTimeDelta;
    float iFrameRate;
    int iFrame;

    vec4 iMouse;
    vec4 iDate;

    float iChannelTime[4];
    vec3 iChannelResolution[4];
};

layout(location = 0) out vec4 outColor;

#line 1
]=])

set(SHADERTOY_FOOTER [=[

void main()
{
    mainImage(outColor, gl_FragCoord.xy);
}
]=])

file(
        WRITE
        "${OUTPUT_FILE}"
        "${SHADERTOY_HEADER}\n${SHADERTOY_SOURCE}\n${SHADERTOY_FOOTER}\n"
)