if(NOT DEFINED INPUT_FILE)
    message(FATAL_ERROR "INPUT_FILE is required")
endif()

if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is required")
endif()

file(READ "${INPUT_FILE}" SHADERTOY_SOURCE)

set(SHADERTOY_COMMON_SOURCE "")

if(DEFINED COMMON_FILE AND EXISTS "${COMMON_FILE}")
    file(
            READ
            "${COMMON_FILE}"
            SHADERTOY_COMMON_SOURCE
    )

    string(
            REPLACE
            "\r\n"
            "\n"
            SHADERTOY_COMMON_SOURCE
            "${SHADERTOY_COMMON_SOURCE}"
    )

    string(
            REPLACE
            "\r"
            "\n"
            SHADERTOY_COMMON_SOURCE
            "${SHADERTOY_COMMON_SOURCE}"
    )
endif()

get_filename_component(OUTPUT_DIR "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")

set(SHADERTOY_HEADER [=[
#version 450

#include "aiko_descriptor_abi.glsl"

// Generated by Aiko's ShaderToy adapter.
// Do not edit this generated file directly.

layout(
    set = AIKO_GRAPHICS_MATERIAL_SET,
    binding = AIKO_MATERIAL_UBO_BINDING,
    std140
) uniform ShaderToyUniforms
{
    vec3 iResolution;
    float iTime;

    float iTimeDelta;
    float iFrameRate;
    int iFrame;

    vec4 iMouse;
    vec4 iDate;

    float iChannelTime[4];
    vec3 iChannelResolution[4];
};

layout(
    set = AIKO_GRAPHICS_MATERIAL_SET,
    binding = AIKO_MATERIAL_TEXTURE_BINDING + 0
) uniform sampler2D iChannel0;

layout(
    set = AIKO_GRAPHICS_MATERIAL_SET,
    binding = AIKO_MATERIAL_TEXTURE_BINDING + 1
) uniform sampler2D iChannel1;

layout(
    set = AIKO_GRAPHICS_MATERIAL_SET,
    binding = AIKO_MATERIAL_TEXTURE_BINDING + 2
) uniform sampler2D iChannel2;

layout(
    set = AIKO_GRAPHICS_MATERIAL_SET,
    binding = AIKO_MATERIAL_TEXTURE_BINDING + 3
) uniform sampler2D iChannel3;

layout(location = 0) out vec4 outColor;

#line 1
]=])

set(SHADERTOY_FOOTER [=[

void main()
{
    mainImage(outColor, gl_FragCoord.xy);
}
]=])

set(SHADERTOY_GENERATED_SOURCE "${SHADERTOY_HEADER}\n")

if(NOT SHADERTOY_COMMON_SOURCE STREQUAL "")
    string(
            APPEND
            SHADERTOY_GENERATED_SOURCE
            "// ShaderToy Common\n"
            "#line 1\n"
            "${SHADERTOY_COMMON_SOURCE}\n\n"
    )
endif()

string(
        APPEND
        SHADERTOY_GENERATED_SOURCE
        "// ShaderToy Image\n"
        "#line 1\n"
        "${SHADERTOY_SOURCE}\n"
        "${SHADERTOY_FOOTER}\n"
)

file(
        WRITE
        "${OUTPUT_FILE}"
        "${SHADERTOY_GENERATED_SOURCE}"
)
